export enum AppErrorCodes{
    INVALID_CREDENTIALS="INVALID_CREDENTIALS",
    SESSION_EXPIRED="SESSION_EXPIRED",
    INTERNAL_ERROR="INTERNAL_ERROR",
    FORBIDDEN_ERROR="FORBIDDEN_ERROR",
    VALIDATION_ERROR="VALIDATION_ERROR",
    NOT_FOUND="NOT_FOUND",
    BLOCKED="BLOCKED",
    INVALID_AUTH="INVALID_AUTH",
    INVALID_OTP="INVALID_OTP",
    EMAIL_ALREADY_USED="EMAIL_ALREADY_USED",
    OVERLAPPING_AVAILABILITY_RULE="OVERLAPPING_AVAILABILITY_RULE",
    INVALID_INPUT="INVALID_INPUT",
    CONFLICT="CONFLICTING_ACTION"
}